name: Build and Deploy
on:
  push:
    branches:
      - production
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies and Build
      run: | # clean install
        npm ci
        npm run build --prod
    - name: Deploy
      run: npx angular-cli-ghpages --dir=docs --no-silent
      env: # CI: true means clean install
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
